classDef normalSkillGroup stroke-width:4px,stroke:#F3D5B5,fill:#FFEDD8;
classDef beingLearnedSkill stroke-width:2px,stroke:#D4A276,fill:#E7BC91;
classDef learnedSkill stroke-width:2px,stroke:#A47148,fill:#BC8A5F;

classDef newSkillGroup stroke-width:4px,stroke:#D6CCC2,fill:#EDEDE9;
classDef newSkill stroke-width:2px,stroke:#D6CCC2,fill:#EDEDE9;
classDef unknownSkill stroke-width:2px,stroke:#D6CCC2,fill:#EDEDE9;

%% https://www.w3schools.com/colors/colors_groups.asp
linkStyle default stroke-width:2px,stroke:BurlyWood;