classDef normalSkillGroup stroke-width:4px,stroke:#DCEBCA,fill:#E9F5DB;
classDef beingLearnedSkill stroke-width:2px,stroke:#C2D5AA,fill:#CFE1B9;
classDef learnedSkill stroke-width:2px,stroke:#A6B98B,fill:#B5C99A;

classDef newSkillGroup stroke-width:4px,stroke:#D6CCC2,fill:#EDEDE9;
classDef newSkill stroke-width:2px,stroke:#D6CCC2,fill:#EDEDE9;
classDef unknownSkill stroke-width:2px,stroke:#D6CCC2,fill:#EDEDE9;

%% https://www.w3schools.com/colors/colors_groups.asp
linkStyle default stroke-width:2px,stroke:OliveDrab;