classDef normalSkillGroup stroke-width:4px,stroke:#FF97B7,fill:#FADDE1;
classDef beingLearnedSkill stroke-width:2px,stroke:#FF87AB,fill:#FFC4D6;
classDef learnedSkill stroke-width:2px,stroke:#FF5D8F,fill:#FF5D8F;

classDef newSkillGroup stroke-width:4px,stroke:#D6CCC2,fill:#EDEDE9;
classDef newSkill stroke-width:2px,stroke:#D6CCC2,fill:#EDEDE9;
classDef unknownSkill stroke-width:2px,stroke:#D6CCC2,fill:#EDEDE9;

%% https://www.w3schools.com/colors/colors_groups.asp
linkStyle default stroke-width:2px,stroke:PaleVioletRed;